# Generated by Django 4.0.6 on 2022-08-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transactionId',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
